### PR TITLE
implement overflow menu

### PR DESCRIPTION
**Pull request by Andi1986**

### CODE REVIEW

**Comment by Andi1986** [comment]
@jeremeamia after you merge this into master, can you please create a new Tag also? I want to use that version in my project :) thanks

**Review by jeremeamia — APPROVED** [review]
Nice! Thanks!

**Comment by Andi1986** [comment]
@jeremeamia Create a release please :)

**Comment by jeremeamia** [comment]
@Andi1986 I would like to merge #12 before I tag

**Pull request merged**
